name: flutter_rakuten_point2
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  isar: ^3.1.0+1

  isar_generator: ^3.1.0+1

  path_provider: ^2.1.1

#  isar_flutter_libs: ^3.1.0+1
  xxf_isar_flutter_libs: ^3.1.0+3

  http: ^1.2.2
  intl: ^0.20.2
  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.5.2
  json_annotation: ^4.9.0
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.8
  bubble: ^1.2.1
  fl_chart: ^0.71.0
  drag_and_drop_lists: ^0.4.1
  flutter_colorpicker: ^1.0.3

  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  scroll_to_index: ^3.0.1
  external_path: ^2.2.0
  charset_converter: ^2.3.0
  scrollable_positioned_list: ^0.3.8
  share_plus: ^11.0.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  file_picker: ^10.1.2
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1

flutter:

  uses-material-design: true
